export const AGREGAR_REGISTRO = 'AGREGAR_REGISTRO';
export const AGREGAR_REGISTRO_EXITO = 'AGREGAR_REGISTRO_EXITO';
export const AGREGAR_REGISTRO_ERROR = 'AGREGAR_REGISTRO_ERROR';


export const COMENZAR_DESCARGA_REGISTROS = 'COMENZAR_DESCARGA_REGISTROS';
export const DESCARGA_REGISTROS_EXITO = 'DESCARGA_REGISTROS_EXITO';
export const DESCARGA_REGISTROS_ERROR = 'DESCARGA_REGISTROS_ERROR';

export const OBTENER_REGISTRO_ELIMINAR = 'OBTENER_REGISTRO_ELIMINAR';
export const REGISTRO_ELIMINADO_EXITO = 'REGISTRO_ELIMINADO_EXITO';
export const REGISTRO_ELIMINADO_ERROR = 'REGISTRO_ELIMINADO_ERROR';


export const OBTENER_REGISTRO_EDITAR = 'OBTENER_REGISTRO_EDITAR';
export const COMENZAR_EDICION_REGISTRO = 'COMENZAR_EDICION_REGISTRO';
export const REGISTRO_EDITADO_EXITO = 'REGISTRO_EDITADO_EXITO';
export const REGISTRO_EDITADO_ERROR = 'REGISTRO_EDITADO_ERROR';

export const MOSTRAR_ALERTA ='MOSTRAR_ALERTA';
export const OCULTAR_ALERTA ='OCULTAR_ALERTA';